name: napari_bioimage_analysis3
channels:
  - conda-forge
  - apple
  - defaults
dependencies:
  - absl-py
  - aiohttp
  - aiosignal
  - alabaster
  - aom
  - apoc-backend
  - app-model
  - appdirs
  - appnope
  - arrow-cpp
  - asciitree
  - asttokens
  - astunparse
  - async-timeout
  - attrs
  - autopep8
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - blinker
  - blosc
  - bokeh
  - brotli
  - brotli-bin
  - brunsli
  - bzip2
  - c-ares
  - c-blosc2
  - ca-certificates
  - cached-property
  - cached_property
  - cachetools
  - cachey
  - cairo
  - cellpose
  - cellpose-napari
  - certifi
  - cffi
  - cfitsio
  - charls
  - charset-normalizer
  - click
  - cloudpickle
  - colorama
  - comm
  - contourpy
  - cryptography
  - csbdeep
  - cycler
  - cython
  - cytoolz
  - dask
  - dask-core
  - dav1d
  - debugpy
  - decorator
  - deprecated
  - distributed
  - docstring_parser
  - docutils
  - eigen
  - entrypoints
  - executing
  - expat
  - fasteners
  - fastremap
  - ffmpeg
  - fftw
  - filelock
  - flatbuffers
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freetype-py
  - frozenlist
  - fsspec
  - gast
  - geometry3d
  - gettext
  - gflags
  - giflib
  - glib
  - glib-tools
  - glog
  - gmp
  - gmpy2
  - gnutls
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - graphite2
  - grpcio
  - gst-plugins-base
  - gstreamer
  - h5py
  - harfbuzz
  - hdbscan
  - hdf5
  - heapdict
  - hsluv
  - icu
  - idna
  - imagecodecs
  - imageio
  - imagesize
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - in-n-out
  - ipycanvas
  - ipyevents
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jasper
  - jedi
  - jinja2
  - joblib
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyterlab_widgets
  - jxrlib
  - keras
  - keras-preprocessing
  - khronos-opencl-icd-loader
  - kiwisolver
  - krb5
  - lame
  - laptrack
  - lazy_loader
  - lcms2
  - lerc
  - libabseil
  - libaec
  - libavif
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libclang13
  - libcrc32c
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libgoogle-cloud
  - libgrpc
  - libiconv
  - libidn2
  - libitk
  - liblapack
  - liblapacke
  - libllvm14
  - libnghttp2
  - libogg
  - libopenblas
  - libopencv
  - libopus
  - libpng
  - libpq
  - libprotobuf
  - libsodium
  - libsqlite
  - libssh2
  - libtasn1
  - libthrift
  - libtiff
  - libunistring
  - libutf8proc
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - libzopfli
  - littleutils
  - llvm-openmp
  - llvmlite
  - locket
  - loguru
  - lz4
  - lz4-c
  - magicgui
  - mako
  - markdown
  - markdown-it-py
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - mdurl
  - mpc
  - mpfr
  - mpmath
  - msgpack-python
  - multidict
  - munkres
  - mypy_extensions
  - mysql-common
  - mysql-libs
  - napari
  - napari-accelerated-pixel-and-object-classification
  - napari-annotator
  - napari-assistant
  - napari-bleach-correct
  - napari-brightness-contrast
  - napari-clusters-plotter
  - napari-console
  - napari-crop
  - napari-feature-classifier
  - napari-filament-annotator
  - napari-laptrack
  - napari-layer-details-display
  - napari-picasso
  - napari-plugin-engine
  - napari-pystackreg
  - napari-simpleitk-image-processing
  - napari-skimage-regionprops
  - napari-svg
  - napari-time-slicer
  - napari-tools-menu
  - napari-workflows
  - natsort
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - npe2
  - nspr
  - nss
  - numba
  - numcodecs
  - numpy
  - numpydoc
  - oauthlib
  - opencv
  - openh264
  - openjpeg
  - openssl
  - opt_einsum
  - orc
  - outdated
  - p11-kit
  - packaging
  - pandas
  - pandas-flavor
  - parquet-cpp
  - parso
  - partd
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pingouin
  - pint
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - ply
  - pooch
  - prompt-toolkit
  - prompt_toolkit
  - protobuf
  - psutil
  - psygnal
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - py-opencv
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pyclesperanto-prototype
  - pycodestyle
  - pycparser
  - pydantic
  - pygments
  - pyjwt
  - pynndescent
  - pyopencl
  - pyopengl
  - pyopenssl
  - pyparsing
  - pyperclip
  - pyproject_hooks
  - pyqt
  - pyqt5-sip
  - pyqtgraph
  - pyrsistent
  - pysocks
  - pystackreg
  - python
  - python-build
  - python-dateutil
  - python-flatbuffers
  - python-tzdata
  - python_abi
  - pytomlpp
  - pytools
  - pytorch
  - pytz
  - pyu2f
  - pywavelets
  - pyyaml
  - pyzmq
  - qt-main
  - qtconsole-base
  - qtpy
  - re2
  - readline
  - requests
  - requests-oauthlib
  - rich
  - rsa
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - setuptools
  - shellingham
  - simpleitk
  - sip
  - six
  - sleef
  - snappy
  - snowballstemmer
  - sortedcontainers
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sqlite
  - stack_data
  - stackview
  - stardist
  - stardist-napari
  - statsmodels
  - superqt
  - svt-av1
  - sympy
  - tabulate
  - tbb
  - tblib
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - termcolor
  - threadpoolctl
  - tifffile
  - tk
  - toml
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - transforms3d
  - typer
  - typing-extensions
  - typing_extensions
  - tzdata
  - umap-learn
  - unicodedata2
  - urllib3
  - vispy
  - wcwidth
  - werkzeug
  - wheel
  - widgetsnbextension
  - wrapt
  - x264
  - x265
  - xarray
  - xorg-libxau
  - xorg-libxdmcp
  - xyzservices
  - xz
  - yaml
  - yarl
  - zarr
  - zeromq
  - zfp
  - zict
  - zipp
  - zlib
  - zlib-ng
  - zstd
  - pip:
    - macro-kit
    - magic-class
    - napari-filaments
