name: napari_bioimage_analysis3
channels:
  - conda-forge
  - apple
  - defaults
dependencies:
  - absl-py=1.4.0
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - alabaster=0.7.13
  - aom=3.5.0
  - apoc-backend=0.12.0
  - app-model=0.1.4
  - appdirs=1.4.4
  - appnope=0.1.3
  - arrow-cpp=7.0.1
  - asciitree=0.3.3
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=23.1.0
  - autopep8=2.0.2
  - aws-c-auth=0.6.28
  - aws-c-cal=0.5.27
  - aws-c-common=0.8.20
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.0
  - aws-c-http=0.7.8
  - aws-c-io=0.13.26
  - aws-c-mqtt=0.8.13
  - aws-c-s3=0.3.4
  - aws-c-sdkutils=0.1.10
  - aws-checksums=0.1.16
  - aws-crt-cpp=0.20.2
  - aws-sdk-cpp=1.10.57
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - blinker=1.6.2
  - blosc=1.21.4
  - bokeh=3.2.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.9.3
  - ca-certificates=2023.5.7
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.0
  - cachey=0.2.1
  - cairo=1.16.0
  - cellpose=2.0.5
  - cellpose-napari=0.1.5
  - certifi=2023.5.7
  - cffi=1.15.1
  - cfitsio=4.2.0
  - charls=2.3.4
  - charset-normalizer=3.1.0
  - click=8.1.3
  - cloudpickle=2.2.1
  - colorama=0.4.6
  - comm=0.1.3
  - contourpy=1.1.0
  - cryptography=41.0.1
  - csbdeep=0.7.3
  - cycler=0.11.0
  - cython=0.29.35
  - cytoolz=0.12.0
  - dask=2023.6.1
  - dask-core=2023.6.1
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - deprecated=1.2.14
  - distributed=2023.6.1
  - docstring_parser=0.15
  - docutils=0.17.1
  - eigen=3.4.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fasteners=0.17.3
  - fastremap=1.13.5
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - filelock=3.12.2
  - flatbuffers=22.12.06
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.40.0
  - freetype=2.12.1
  - freetype-py=2.4.0
  - frozenlist=1.3.3
  - fsspec=2023.6.0
  - gast=0.4.0
  - geometry3d=0.2.4
  - gettext=0.21.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - glog=0.6.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.7.8
  - google-auth=2.17.3
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.51.1
  - gst-plugins-base=1.22.4
  - gstreamer=1.22.4
  - h5py=3.8.0
  - harfbuzz=6.0.0
  - hdbscan=0.8.29
  - hdf5=1.12.2
  - heapdict=1.0.1
  - hsluv=5.0.2
  - icu=70.1
  - idna=3.4
  - imagecodecs=2022.9.26
  - imageio=2.31.1
  - imagesize=1.4.1
  - importlib-metadata=6.7.0
  - importlib_metadata=6.7.0
  - importlib_resources=5.12.0
  - in-n-out=0.1.7
  - ipycanvas=0.13.1
  - ipyevents=2.0.1
  - ipykernel=6.23.3
  - ipython=8.14.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jasper=2.0.33
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.3.0
  - jupyter_core=5.3.1
  - jupyterlab_widgets=3.0.7
  - jxrlib=1.1
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - khronos-opencl-icd-loader=2023.04.17
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - laptrack=0.15.1
  - lazy_loader=0.2
  - lcms2=2.14
  - lerc=4.0.0
  - libabseil=20220623.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcrc32c=1.1.2
  - libcurl=8.1.2
  - libcxx=16.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libgoogle-cloud=2.5.0
  - libgrpc=1.51.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libitk=5.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopencv=4.6.0
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.11.0
  - libtasn1=4.19.0
  - libthrift=0.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxml2=2.10.3
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - littleutils=0.2.2
  - llvm-openmp=16.0.6
  - llvmlite=0.40.1
  - locket=1.0.0
  - loguru=0.7.0
  - lz4=4.3.2
  - lz4-c=1.9.4
  - magicgui=0.7.2
  - mako=1.2.4
  - markdown=3.4.3
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - msgpack-python=1.0.5
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - napari=0.4.17
  - napari-accelerated-pixel-and-object-classification=0.12.3
  - napari-annotator=0.0.4
  - napari-assistant=0.4.5
  - napari-bleach-correct=0.0.1
  - napari-brightness-contrast=0.1.8
  - napari-clusters-plotter=0.7.2
  - napari-console=0.0.8
  - napari-crop=0.1.7
  - napari-feature-classifier=0.0.3
  - napari-filament-annotator=0.1.2
  - napari-laptrack=0.2.0
  - napari-layer-details-display=0.1.5
  - napari-picasso=0.3.0
  - napari-plugin-engine=0.2.0
  - napari-pystackreg=0.1.4
  - napari-simpleitk-image-processing=0.4.5
  - napari-skimage-regionprops=0.10.1
  - napari-svg=0.1.10
  - napari-time-slicer=0.4.9
  - napari-tools-menu=0.1.19
  - napari-workflows=0.2.9
  - natsort=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.8.1
  - networkx=2.8.8
  - npe2=0.7.0
  - nspr=4.35
  - nss=3.89
  - numba=0.57.1
  - numcodecs=0.11.0
  - numpy=1.23.5
  - numpydoc=1.5.0
  - oauthlib=3.2.2
  - opencv=4.6.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.1
  - opt_einsum=3.3.0
  - orc=1.8.2
  - outdated=0.2.2
  - p11-kit=0.24.1
  - packaging=23.1
  - pandas=1.5.3
  - pandas-flavor=0.2.0
  - parquet-cpp=1.5.1
  - parso=0.8.3
  - partd=1.4.0
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pingouin=0.5.3
  - pint=0.22
  - pip=23.1.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.8.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=4.21.12
  - psutil=5.9.5
  - psygnal=0.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-opencv=4.6.0
  - pyarrow=7.0.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pyclesperanto-prototype=0.23.6
  - pycodestyle=2.10.0
  - pycparser=2.21
  - pydantic=1.10.9
  - pygments=2.15.1
  - pyjwt=2.7.0
  - pynndescent=0.5.10
  - pyopencl=2023.1.1
  - pyopengl=3.1.6
  - pyopenssl=23.2.0
  - pyparsing=3.1.0
  - pyperclip=1.8.2
  - pyproject_hooks=1.0.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyqtgraph=0.13.3
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - pystackreg=0.2.7
  - python=3.10.0
  - python-build=0.10.0
  - python-dateutil=2.8.2
  - python-flatbuffers=23.5.26
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytomlpp=1.0.13
  - pytools=2023.1
  - pytorch=2.0.0
  - pytz=2023.3
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - qt-main=5.15.8
  - qtconsole-base=5.4.3
  - qtpy=2.3.1
  - re2=2022.06.01
  - readline=8.2
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rich=13.4.2
  - rsa=4.9
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scipy=1.11.0
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=68.0.0
  - shellingham=1.5.1
  - simpleitk=2.2.1
  - sip=6.7.9
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - sphinx=4.5.0
  - sphinxcontrib-applehelp=1.0.4
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.1
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.42.0
  - stack_data=0.6.2
  - stackview=0.6.3
  - stardist=0.8.3
  - stardist-napari=2022.12.6
  - statsmodels=0.14.0
  - superqt=0.4.1
  - svt-av1=1.4.1
  - sympy=1.12
  - tabulate=0.9.0
  - tbb=2021.9.0
  - tblib=1.7.0
  - tensorboard=2.11.2
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - termcolor=2.3.0
  - threadpoolctl=3.1.0
  - tifffile=2022.10.10
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.9.0
  - transforms3d=0.4.1
  - typer=0.9.0
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - umap-learn=0.5.3
  - unicodedata2=15.0.0
  - urllib3=2.0.3
  - vispy=0.11.0
  - wcwidth=0.2.6
  - werkzeug=2.3.6
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - wrapt=1.15.0
  - x264=1!164.3095
  - x265=3.5
  - xarray=2023.6.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.5.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zarr=2.15.0
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.15.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zstd=1.5.2
  - pip:
    - macro-kit==0.4.5
    - magic-class==0.7.3
    - napari-filaments==0.3.0

